# -*- coding: utf-8 -*-
"""
/***************************************************************************
 HeatMap_PointExtracter
                                 A QGIS plugin
 This Plugin extracts Points of high Point density
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-11-18
        copyright            : (C) 2019 by Ben Everad / Endura kommunal
        email                : ben@everad.lu
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load HeatMap_PointExtracter class from file HeatMap_PointExtracter.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .heatPointExtracter import HeatMap_PointExtracter
    return HeatMap_PointExtracter(iface)
